window.CATEGORIES = [
  { id: "all", title: "Все блюда", icon: "🍽️" },
  { id: "breakfast", title: "Завтраки", icon: "☕" },
  { id: "main", title: "Обеды", icon: "🍲" },
  { id: "dessert", title: "Десерты", icon: "🍓" }
];

window.RECIPES = [
  {
    id: "omelet-cheese-tomato-toast",
    title: "Омлет с сыром, помидором и зеленью + тост",
    category: "breakfast",
    image: "assets/omelet-cheese-tomato-toast.jpg",
    heroImage: "assets/omelet-cheese-tomato-toast.jpg",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "15–20 мин",
    nutrition: { kcal: 390, protein: 24, fat: 21, carbs: 24 },
    ingredients: [
      { name: "Яйца", amount: 4, unit: "шт" },
      { name: "Молоко", amount: 50, unit: "мл" },
      { name: "Сыр", amount: 50, unit: "г" },
      { name: "Помидоры", amount: 150, unit: "г" },
      { name: "Зелень", amount: 10, unit: "г" },
      { name: "Растительное масло", amount: 5, unit: "г" },
      { name: "Хлеб для тостов", amount: 80, unit: "г" }
    ],
    steps: ["Взбить яйца с молоком, солью и перцем.", "Помидоры нарезать и слегка прогреть на сковороде.", "Влить яйца, добавить сыр и зелень.", "Готовить 5–7 минут и подать с тостами."],
    notes: []
  },
  {
    id: "cottage-cheese-banana-berries-honey",
    title: "Творог с бананом, ягодами, орехами и мёдом",
    category: "breakfast",
    image: "assets/cottage-cheese-banana-berries-honey.jpg",
    heroImage: "assets/cottage-cheese-banana-berries-honey.jpg",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "5–7 мин",
    nutrition: { kcal: 405, protein: 33, fat: 16, carbs: 33 },
    ingredients: [
      { name: "Творог 5%", amount: 350, unit: "г" },
      { name: "Бананы", amount: 120, unit: "г" },
      { name: "Ягоды", amount: 120, unit: "г" },
      { name: "Орехи", amount: 25, unit: "г" },
      { name: "Мёд", amount: 15, unit: "г" },
      { name: "Йогурт натуральный", amount: 40, unit: "г" }
    ],
    steps: ["Разложить творог по двум мискам.", "Добавить банан и ягоды.", "Посыпать орехами.", "Полить мёдом и при желании добавить йогурт."],
    notes: []
  },
  {
    id: "egg-cheese-tomato-salad-sandwich",
    title: "Сэндвич с яйцом, сыром, помидором и салатом",
    category: "breakfast",
    image: "assets/egg-cheese-tomato-salad-sandwich.jpg",
    heroImage: "assets/egg-cheese-tomato-salad-sandwich.jpg",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "15–20 мин",
    nutrition: { kcal: 350, protein: 18, fat: 17, carbs: 28 },
    ingredients: [
      { name: "Хлеб для тостов", amount: 100, unit: "г" },
      { name: "Яйца", amount: 2, unit: "шт" },
      { name: "Сыр", amount: 50, unit: "г" },
      { name: "Помидоры", amount: 120, unit: "г" },
      { name: "Листья салата", amount: 20, unit: "г" },
      { name: "Творожный сыр", amount: 30, unit: "г" }
    ],
    steps: ["Яйца отварить или пожарить.", "Хлеб подсушить.", "Намазать творожный сыр.", "Выложить салат, яйцо, сыр и помидор.", "Накрыть вторым ломтиком и разрезать пополам."],
    notes: []
  },
  {
    id: "oatmeal-fruits-nuts",
    title: "Овсянка с фруктами и орехами",
    category: "breakfast",
    image: "assets/oatmeal-fruits-nuts.jpg",
    heroImage: "assets/oatmeal-fruits-nuts.jpg",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "10–15 мин",
    nutrition: { kcal: 465, protein: 15, fat: 16, carbs: 66 },
    ingredients: [
      { name: "Овсяные хлопья", amount: 100, unit: "г" },
      { name: "Молоко", amount: 400, unit: "мл" },
      { name: "Бананы", amount: 120, unit: "г" },
      { name: "Ягоды", amount: 100, unit: "г" },
      { name: "Орехи", amount: 25, unit: "г" },
      { name: "Мёд", amount: 15, unit: "г" }
    ],
    steps: ["Довести молоко до кипения.", "Добавить овсяные хлопья и варить 5–7 минут.", "Разложить по тарелкам.", "Сверху добавить банан, ягоды, орехи и мёд."],
    notes: ["Молоко можно заменить водой."]
  },
  {
    id: "oat-pancakes-berries",
    title: "Овсяные оладьи с ягодами",
    category: "breakfast",
    image: "assets/oat-pancakes-berries.jpg",
    heroImage: "assets/oat-pancakes-berries.jpg",
    portions: 1,
    meta: "на 1 порцию",
    servingNote: "≈ 4–5 шт",
    cookTime: "30–40 мин",
    nutrition: { kcal: 518, protein: 27, fat: 23, carbs: 48 },
    ingredients: [
      { name: "Овсяные хлопья", amount: 55, unit: "г" },
      { name: "Яйца", amount: 1, unit: "шт" },
      { name: "Творог 5%", amount: 55, unit: "г" },
      { name: "Малина", amount: 55, unit: "г" },
      { name: "Голубика", amount: 55, unit: "г" },
      { name: "Подсластитель", amount: null, unit: "по вкусу" },
      { name: "Разрыхлитель", amount: 5, unit: "г" },
      { name: "Сметана 10%", amount: 110, unit: "г" }
    ],
    steps: ["Обдать ягоды кипятком и обсушить.", "Смешать овсяные хлопья, яйцо, творог, ягоды, сахарозаменитель и разрыхлитель.", "Пробить массу блендером до однородности.", "Дать тесту постоять 10–20 минут.", "Выпекать оладьи на слегка смазанной сковороде на среднем огне с двух сторон.", "Подавать со сметаной."],
    notes: []
  },
  {
    id: "lavash-roll-egg-cheese-vegetables",
    title: "Лаваш-ролл с яйцом, сыром и овощами",
    category: "breakfast",
    image: "assets/lavash-roll-egg-cheese-vegetables.jpg",
    heroImage: "assets/lavash-roll-egg-cheese-vegetables.jpg",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "15–20 мин",
    nutrition: { kcal: 403, protein: 24, fat: 17, carbs: 33 },
    ingredients: [
      { name: "Лаваш", amount: 100, unit: "г" },
      { name: "Яйца", amount: 3, unit: "шт" },
      { name: "Сыр", amount: 60, unit: "г" },
      { name: "Огурцы", amount: 120, unit: "г" },
      { name: "Помидоры", amount: 120, unit: "г" },
      { name: "Листья салата", amount: 20, unit: "г" },
      { name: "Йогурт натуральный", amount: 30, unit: "г" }
    ],
    steps: ["Яйца приготовить как скрэмбл.", "Овощи нарезать.", "Лаваш смазать йогуртом, добавить салат, яйца, сыр и овощи.", "Завернуть рулетом и слегка прогреть."],
    notes: []
  },
  {
    id: "toast-cottage-cheese-egg-cucumber",
    title: "Тосты с творожным сыром, яйцом и огурцом",
    category: "breakfast",
    image: "assets/toast-cream-cheese-egg-cucumber.jpg",
    heroImage: "",
    portions: 2,
    meta: "на 2 порции",
    servingNote: "2 шт",
    cookTime: "10–12 мин",
    nutrition: { kcal: 332, protein: 14, fat: 17, carbs: 29 },
    ingredients: [
      { name: "Хлеб для тостов", amount: 100, unit: "г" },
      { name: "Творожный сыр", amount: 90, unit: "г" },
      { name: "Яйца", amount: 2, unit: "шт" },
      { name: "Огурцы", amount: 120, unit: "г" },
      { name: "Зелень", amount: 10, unit: "г" }
    ],
    steps: ["Подсушить хлеб.", "Намазать творожный сыр.", "Добавить яйцо и огурец.", "Посыпать зеленью и подать."],
    notes: []
  },
  {
    id: "mini-cottage-cheese-casserole",
    title: "Мини-творожная запеканка",
    category: "breakfast",
    image: "assets/mini-cottage-cheese-casserole.jpg",
    heroImage: "assets/mini-cottage-cheese-casserole.jpg",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "40–45 мин",
    nutrition: { kcal: 313, protein: 30, fat: 11, carbs: 25 },
    ingredients: [
      { name: "Творог", amount: 300, unit: "г" },
      { name: "Яйца", amount: 1, unit: "шт" },
      { name: "Манка", amount: 20, unit: "г" },
      { name: "Сахар", amount: 20, unit: "г" },
      { name: "Йогурт натуральный", amount: 30, unit: "г" },
      { name: "Ягоды", amount: 50, unit: "г" }
    ],
    steps: ["Смешать творог, яйцо, сахар и йогурт.", "Добавить манку и оставить на 10 минут.", "Выложить в форму и запекать 25–30 минут при 180°C."],
    notes: ["Манку можно заменить мукой."]
  },
  {
    id: "yogurt-bowl",
    title: "Йогуртовый боул",
    category: "breakfast",
    image: "assets/yogurt-bowl.jpg",
    heroImage: "",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "5–7 мин",
    nutrition: { kcal: 398, protein: 14, fat: 16, carbs: 55 },
    ingredients: [
      { name: "Йогурт натуральный", amount: 350, unit: "г" },
      { name: "Бананы", amount: 120, unit: "г" },
      { name: "Гранола", amount: 70, unit: "г" },
      { name: "Орехи", amount: 20, unit: "г" },
      { name: "Мёд", amount: 10, unit: "г" },
      { name: "Ягоды", amount: 50, unit: "г" }
    ],
    steps: ["Разложить йогурт по мискам.", "Добавить банан.", "Посыпать гранолой, орехами и ягодами.", "Полить мёдом."],
    notes: ["Гранолу можно заменить мюсли."]
  },
  {
    id: "scramble-bread-vegetables",
    title: "Скрэмбл + хлеб + овощи",
    category: "breakfast",
    image: "assets/scramble-bread-vegetables.jpg",
    heroImage: "",
    portions: 2,
    meta: "на 2 порции",
    cookTime: "10–12 мин",
    nutrition: { kcal: 287, protein: 19, fat: 12, carbs: 25 },
    ingredients: [
      { name: "Яйца", amount: 4, unit: "шт" },
      { name: "Молоко", amount: 30, unit: "мл" },
      { name: "Хлеб для тостов", amount: 80, unit: "г" },
      { name: "Огурцы", amount: 120, unit: "г" },
      { name: "Помидоры", amount: 150, unit: "г" }
    ],
    steps: ["Взбить яйца с молоком.", "Готовить на слабом огне, постоянно помешивая.", "Подать с хлебом и свежими овощами."],
    notes: []
  },
  {
    id: "chicken-meatballs-potato-salad",
    title: "Куриные тефтели с картошкой дольками и салатом",
    category: "main",
    image: "assets/chicken-meatballs-potato-salad.jpg",
    heroImage: "assets/chicken-meatballs-potato-salad.jpg",
    portions: 6,
    meta: "на 2 человек на 2–3 дня",
    cookTime: "50–60 мин",
    nutrition: { kcal: 495, protein: 31, fat: 18, carbs: 51 },
    ingredients: [
      { name: "Куриный фарш", amount: 800, unit: "г" },
      { name: "Яйца", amount: 1, unit: "шт" },
      { name: "Лук", amount: 100, unit: "г" },
      { name: "Чеснок", amount: 2, unit: "зубч." },
      { name: "Панировочные сухари", amount: 30, unit: "г" },
      { name: "Паприка", amount: 1, unit: "ч. л." },
      { name: "Соль", amount: null, unit: "по вкусу" },
      { name: "Перец", amount: null, unit: "по вкусу" },
      { name: "Картофель", amount: 1200, unit: "г" },
      { name: "Растительное масло", amount: 35, unit: "г" },
      { name: "Огурцы", amount: 240, unit: "г" },
      { name: "Помидоры", amount: 500, unit: "г" },
      { name: "Листья салата", amount: 200, unit: "г" },
      { name: "Йогурт натуральный", amount: 100, unit: "г" }
    ],
    steps: ["Смешать фарш с яйцом, луком, чесноком и специями.", "Сформировать тефтели.", "Картофель нарезать дольками и смешать с маслом.", "Запечь тефтели и картошку при 200°C 35–45 минут.", "Подать со свежим салатом и йогуртовой заправкой."],
    notes: ["Выход: 6 порций.", "Салат лучше готовить свежим.", "Удобно разложить по контейнерам."]
  },
  {
    id: "pilaf-light-chicken-bulgur",
    title: "Плов-лайт с курицей и булгуром",
    category: "main",
    image: "assets/chicken-bulgur-light-plov.jpg",
    heroImage: "",
    portions: 6,
    meta: "на 2 человек на 2–3 дня",
    cookTime: "35–45 мин",
    nutrition: { kcal: 461, protein: 39, fat: 11, carbs: 51 },
    ingredients: [
      { name: "Куриное филе", amount: 800, unit: "г" },
      { name: "Булгур", amount: 350, unit: "г" },
      { name: "Морковь", amount: 300, unit: "г" },
      { name: "Лук", amount: 200, unit: "г" },
      { name: "Чеснок", amount: 3, unit: "зубч." },
      { name: "Растительное масло", amount: 35, unit: "г" },
      { name: "Специи для плова", amount: 10, unit: "г" },
      { name: "Соль", amount: null, unit: "по вкусу" },
      { name: "Перец", amount: null, unit: "по вкусу" }
    ],
    steps: ["Курицу нарезать и обжарить до лёгкой корочки.", "Добавить лук и морковь.", "Добавить чеснок и специи.", "Всыпать булгур и залить 750 мл воды.", "Готовить под крышкой 20 минут и дать настояться."],
    notes: ["Выход: 6 порций.", "Булгур делает блюдо легче классического плова.", "Вкусно с овощным салатом."]
  },
  {
    id: "chicken-lavash-vegetables-yogurt-sauce",
    title: "Курица в лаваше с овощами и йогуртовым соусом",
    category: "main",
    image: "assets/chicken-lavash-vegetables-yogurt.jpg",
    heroImage: "",
    portions: 6,
    meta: "на 2 человек на 2–3 дня",
    cookTime: "25–30 мин",
    nutrition: { kcal: 411, protein: 39, fat: 9, carbs: 38 },
    ingredients: [
      { name: "Лаваш", amount: 300, unit: "г" },
      { name: "Куриное филе", amount: 800, unit: "г" },
      { name: "Огурцы", amount: 350, unit: "г" },
      { name: "Помидоры", amount: 500, unit: "г" },
      { name: "Листья салата", amount: 200, unit: "г" },
      { name: "Растительное масло", amount: 15, unit: "г" },
      { name: "Йогурт натуральный", amount: 300, unit: "г" },
      { name: "Чеснок", amount: 3, unit: "зубч." },
      { name: "Зелень", amount: 20, unit: "г" },
      { name: "Соль", amount: null, unit: "по вкусу" },
      { name: "Перец", amount: null, unit: "по вкусу" }
    ],
    steps: ["Курицу нарезать, приправить и обжарить.", "Смешать йогурт, чеснок и зелень для соуса.", "Овощи нарезать.", "На лаваш выложить салат, курицу, овощи и соус.", "Завернуть и при желании слегка подрумянить."],
    notes: ["Выход: 6 порций.", "Лаваш лучше собирать перед подачей.", "Удобно брать с собой."]
  },
  {
    id: "fish-potato-cauliflower-puree",
    title: "Рыба с пюре из картофеля и цветной капусты",
    category: "main",
    image: "assets/fish-potato-cauliflower-puree.jpg",
    heroImage: "assets/fish-potato-cauliflower-puree.jpg",
    portions: 5,
    meta: "на 2 человек на 2 дня",
    cookTime: "40–50 мин",
    nutrition: { kcal: 424, protein: 44, fat: 10, carbs: 37 },
    ingredients: [
      { name: "Филе рыбы", amount: 800, unit: "г" },
      { name: "Лимонный сок", amount: 20, unit: "мл" },
      { name: "Растительное масло", amount: 20, unit: "г" },
      { name: "Картофель", amount: 800, unit: "г" },
      { name: "Цветная капуста", amount: 550, unit: "г" },
      { name: "Молоко", amount: 175, unit: "мл" },
      { name: "Сливочное масло", amount: 35, unit: "г" },
      { name: "Огурцы", amount: 150, unit: "г" },
      { name: "Помидоры", amount: 150, unit: "г" },
      { name: "Зелень", amount: 10, unit: "г" },
      { name: "Соль", amount: null, unit: "по вкусу" },
      { name: "Перец", amount: null, unit: "по вкусу" }
    ],
    steps: ["Картофель и цветную капусту отварить до мягкости.", "Добавить молоко и сливочное масло, сделать пюре.", "Рыбу посолить, поперчить и сбрызнуть лимонным соком.", "Запечь при 190–200°C 15–25 минут.", "Подать с пюре и свежими овощами."],
    notes: ["Выход: 5 порций.", "Пюре получается нежным и лёгким.", "Рыбу можно заменить курицей."]
  },
  {
    id: "beef-vegetables-buckwheat",
    title: "Тушёная говядина с овощами и гречкой",
    category: "main",
    image: "assets/beef-vegetables-buckwheat.jpg",
    heroImage: "assets/beef-vegetables-buckwheat.jpg",
    portions: 6,
    meta: "на 2 человек на 2–3 дня",
    cookTime: "80–100 мин",
    nutrition: { kcal: 503, protein: 34, fat: 23, carbs: 41 },
    ingredients: [
      { name: "Говядина", amount: 800, unit: "г" },
      { name: "Лук", amount: 200, unit: "г" },
      { name: "Морковь", amount: 200, unit: "г" },
      { name: "Сладкий перец", amount: 250, unit: "г" },
      { name: "Кабачки", amount: 300, unit: "г" },
      { name: "Помидоры", amount: 400, unit: "г" },
      { name: "Растительное масло", amount: 30, unit: "г" },
      { name: "Гречка", amount: 300, unit: "г" },
      { name: "Соль", amount: null, unit: "по вкусу" },
      { name: "Перец", amount: null, unit: "по вкусу" }
    ],
    steps: ["Говядину нарезать и обжарить до румяности.", "Добавить лук и морковь.", "Добавить перец, кабачок и томаты.", "Тушить под крышкой 60–90 минут.", "Отдельно сварить гречку и подать вместе."],
    notes: ["Выход: 6 порций.", "Отлично подходит для разогрева.", "Можно менять овощи по сезону."]
  },
  {
    id: "cottage-cheese-strawberry-vatrushki",
    title: "Творожные ватрушки с клубникой",
    category: "dessert",
    image: "assets/cottage-cheese-strawberry-vatrushki.jpg",
    heroImage: "assets/cottage-cheese-strawberry-vatrushki.jpg",
    portions: 1,
    meta: "на 1 порцию",
    servingNote: "4 шт",
    cookTime: "35–45 мин",
    nutrition: { kcal: 625, protein: 55, fat: 18, carbs: 62 },
    ingredients: [
      { name: "Творог", amount: 250, unit: "г" },
      { name: "Яйца", amount: 1, unit: "шт" },
      { name: "Мука", amount: 60, unit: "г" },
      { name: "Разрыхлитель", amount: 2.5, unit: "г" },
      { name: "Подсластитель", amount: null, unit: "по вкусу" },
      { name: "Клубника", amount: 150, unit: "г" }
    ],
    steps: [
      "Смешать 200 г творога с яйцом, разрыхлителем и подсластителем.",
      "Добавить муку и замесить мягкую массу.",
      "Оставшиеся 50 г творога смешать с подсластителем для начинки.",
      "Сформировать 4 шарика, выложить на пергамент и стаканом сделать углубления.",
      "В углубления добавить творожную начинку, сверху выложить клубнику.",
      "Выпекать при 200°C около 30 минут."
    ],
    notes: ["Выход: 4 ватрушки.", "КБЖУ указаны примерно на весь рецепт."]
  }
];